language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- pypy
- pypy3
install:
- pip install .
- pip install -r requirements.txt
script: python -m unittest discover
deploy:
  provider: pypi
  user: "__token__"
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
  password:
    secure: "H8L6Pz7zI9K2IhaStM47kX0B5aUoAsX5gDN615V04W8LuWByENTIRSdjebTzk/A9FcOnppW84XzbTvLhJV3VJ1VD3SK+tw5Cqa73Q//nYaIo1xE4AixiCMfFh9xg/FxO4d9TUXMzLpF3hRqB0l9DaGAbDgyo24jgQ55oj5WUuv4XL4ZvjxK6l8dQJV1sKdM6MuRtVTy+GqcR3nX0vLTzz/MzVygKst6heVFzKEGv7IR3iy4S4xhsRl2aRU7iq2k+59au1FfjsttaRCWKOO69+TfVHSz4k6aNQPuIk9Iu81pVORzJAe9swTzshyfl3SVOtDgBECzwI4VM5HbFXKA08XJVzcnAy0c1BozhSub3Ao9W5XPOEzv4G88f5H/dgTlIOd7AcwzM267E4TsJUgzjWlDameTM+LhpaT44uhw/I6yw1Pl9Znjz1dltxujrpakyTXQkwzb456L0jhvE/ErwI3D06BVj6ZOvUvkEpGyMYJP0RRRzH/VjKNt3M1B+Swf/+qBFjGVahHU2Dn3jR/cy+gYKasAz87Q6E1r/xlZfIsI/1LTa9psIReDYhEc1vFqMIk6kKQaKURF+JEkAy0u9B/uunVIdDTpDVFOD991EdlQSpaiXaff77Ydw1uxcgahzZpDB1NwCJK4YuuKNasU1kQsvopTs7XlaROUEG/KXiz4="
